// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpgtsyztgmsaybzfhlrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZ3RzeXp0Z21zYXliemZobHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTUwODksImV4cCI6MjA2MzI3MTA4OX0.dy3FY_HJNbIVZ8SuAEcN70-73hUVVgRuvdWfvFAAI-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);